    public static void rLinear(int numInst, int numAttr, FileType ft){ //'Linearna enacba: A1 + 2*A2 + 3*A3 = R'
        double tab[]=new double[numAttr+1]; //A1,A2,A3,A4,A5,class
       
        switch(ft){
            case CSV: for(int i=0;i<tab.length;i++){
                        if(i==tab.length-1)
                            outFile.print("class");
                        else
                            outFile.print("A"+(i+1)+",");
                     }
                    outFile.println();
                    break;
            case ARFF:
                       outFile.println("@relation 'Linear function: A1 + 2*A2 + 3*A3 = R' ");
                       outFile.println();
                       for(int i=0;i<tab.length;i++){
                        if(i==tab.length-1)
                            outFile.println("@attribute class numeric");
                        else
                            outFile.println("@attribute A"+(i+1)+" numeric");
                    }
                    outFile.println();
                    outFile.println("@data");
                    break;
        }
       
        for (int i=0;i<numInst;i++){
            for(int j=0;j<tab.length-1;j++){    //class value is calculated not generated by random
                tab[j]=Math.random()*100;
            }
            tab[tab.length-1]=tab[0]+2*tab[1]+3*tab[2]; //A1 + 2*A2 + 3*A3 = R
            print1dToF(tab);
        }
    }